version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn 'src.main:app' --reload --host=0.0.0.0 --port=8005"
    env_file:
    - .env
    ports:
      - 8005:8005
    # peristance des données
    volumes:
      - .:/app