name: snow_fastapi_deploy
run-name: ${{github.actor}} is learning Githbub Actions

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        
        paths:
            - .github/workflows/
            - src/**
            - tests/**

env:
    APP_NAME: "app_deploy"
    APP_PORT: "8080"
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.11
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
            - name: Install requirements
              run: |
                pip install -r requirements.txt
            - name: lint with ruff
              run: |
                pip install ruff
                
            
